#ifndef CHAINPARAMSSEEDS_H
#define CHAINPARAMSSEEDS_H
// List of fixed seed nodes for the bitcoin network
// AUTOGENERATED by contrib/devtools/generate-seeds.py

// Each line contains a 16-byte IPv6 address and a port.
// IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
static const unsigned int pnSeed[] =
{
   0x63ECD7E3, //215.227
   0xC61B61AC, //97.172
   0xC632F359, //243.89
   0xC632F35A, //243.90
};


static const unsigned int pnTestnetSeed[] = {

};
#endif
